# Chakra data information
chakra_data = [
    {
        "name": "Root",
        "name_ru": "Корневая",
        "sanskrit_name": "Muladhara",
        "sanskrit_name_ru": "Муладхара",
        "color_rgb": [255, 0, 0],
        "color_hex": "#FF0000",
        "location": "Base of spine",
        "location_ru": "Основание позвоночника",
        "element": "Earth",
        "element_ru": "Земля",
        "associated_with": "Survival, grounding, stability, basic needs",
        "associated_with_ru": "Выживание, заземление, стабильность, базовые потребности",
        "balanced_qualities": "Security, stability, grounded, confident",
        "balanced_qualities_ru": "Безопасность, стабильность, заземленность, уверенность",
        "imbalanced_signs": "Fear, anxiety, financial insecurity, disconnection",
        "imbalanced_signs_ru": "Страх, тревога, финансовая нестабильность, разобщенность",
        "healing_practices": "Walking barefoot in nature, physical exercise, red foods, affirmations focusing on safety and security",
        "healing_practices_ru": "Ходьба босиком на природе, физические упражнения, красные продукты, аффирмации на безопасность"
    },
    {
        "name": "Sacral",
        "name_ru": "Сакральная",
        "sanskrit_name": "Svadhisthana",
        "sanskrit_name_ru": "Свадхистхана",
        "color_rgb": [255, 128, 0],
        "color_hex": "#FF8000",
        "location": "Lower abdomen",
        "location_ru": "Нижняя часть живота",
        "element": "Water",
        "element_ru": "Вода",
        "associated_with": "Creativity, sexuality, pleasure, emotional balance",
        "associated_with_ru": "Творчество, сексуальность, удовольствие, эмоциональный баланс",
        "balanced_qualities": "Creative, passionate, emotionally balanced, sensual",
        "balanced_qualities_ru": "Творческий подход, страсть, эмоциональная уравновешенность, чувственность",
        "imbalanced_signs": "Emotional numbness, lack of creativity, sexual dysfunction, reproductive issues",
        "imbalanced_signs_ru": "Эмоциональное онемение, отсутствие творчества, сексуальная дисфункция, репродуктивные проблемы",
        "healing_practices": "Dance, creative expression, hydration, orange foods, emotional release exercises",
        "healing_practices_ru": "Танец, творческое самовыражение, увлажнение, оранжевые продукты, упражнения для эмоциональной разрядки"
    },
    {
        "name": "Solar Plexus",
        "name_ru": "Солнечное сплетение",
        "sanskrit_name": "Manipura",
        "sanskrit_name_ru": "Манипура",
        "color_rgb": [255, 255, 0],
        "color_hex": "#FFFF00",
        "location": "Upper abdomen/stomach area",
        "location_ru": "Верхняя часть живота/область желудка",
        "element": "Fire",
        "element_ru": "Огонь",
        "associated_with": "Personal power, self-esteem, confidence, willpower",
        "associated_with_ru": "Личная сила, самооценка, уверенность, сила воли",
        "balanced_qualities": "Confident, purposeful, disciplined, driven",
        "balanced_qualities_ru": "Уверенность, целеустремленность, дисциплинированность, мотивированность",
        "imbalanced_signs": "Low self-esteem, digestive issues, inability to set boundaries, powerlessness",
        "imbalanced_signs_ru": "Низкая самооценка, проблемы с пищеварением, неспособность устанавливать границы, бессилие",
        "healing_practices": "Core exercises, setting boundaries, yellow foods, affirmations focused on personal power",
        "healing_practices_ru": "Упражнения для кора, установление границ, желтые продукты, аффирмации, направленные на личную силу"
    },
    {
        "name": "Heart",
        "name_ru": "Сердечная",
        "sanskrit_name": "Anahata",
        "sanskrit_name_ru": "Анахата",
        "color_rgb": [0, 255, 0],
        "color_hex": "#00FF00",
        "location": "Center of chest",
        "location_ru": "Центр груди",
        "element": "Air",
        "element_ru": "Воздух",
        "associated_with": "Love, compassion, forgiveness, relationships",
        "associated_with_ru": "Любовь, сострадание, прощение, отношения",
        "balanced_qualities": "Loving, compassionate, forgiving, empathetic",
        "balanced_qualities_ru": "Любящий, сострадательный, прощающий, эмпатичный",
        "imbalanced_signs": "Grief, anger, resentment, fear of intimacy, respiratory issues",
        "imbalanced_signs_ru": "Горе, гнев, обида, страх близости, проблемы с дыханием",
        "healing_practices": "Forgiveness exercises, volunteer work, green foods, heart-opening yoga poses",
        "healing_practices_ru": "Упражнения на прощение, волонтерство, зеленые продукты, йога для открытия сердечной чакры"
    },
    {
        "name": "Throat",
        "name_ru": "Горловая",
        "sanskrit_name": "Vishuddha",
        "sanskrit_name_ru": "Вишудха",
        "color_rgb": [0, 191, 255],
        "color_hex": "#00BFFF",
        "location": "Throat",
        "location_ru": "Горло",
        "element": "Ether",
        "element_ru": "Эфир",
        "associated_with": "Communication, self-expression, truth, authentic voice",
        "associated_with_ru": "Общение, самовыражение, правда, аутентичный голос",
        "balanced_qualities": "Articulate, honest, good listener, authentic expression",
        "balanced_qualities_ru": "Красноречие, честность, хороший слушатель, подлинное самовыражение",
        "imbalanced_signs": "Difficulty speaking truth, throat problems, fear of speaking, inability to express",
        "imbalanced_signs_ru": "Трудности в выражении правды, проблемы с горлом, страх говорить, неспособность выражать себя",
        "healing_practices": "Singing, journaling, speaking truth, blue foods, neck stretches",
        "healing_practices_ru": "Пение, ведение дневника, говорить правду, синие продукты, растяжка шеи"
    },
    {
        "name": "Third Eye",
        "name_ru": "Третий глаз",
        "sanskrit_name": "Ajna",
        "sanskrit_name_ru": "Аджна",
        "color_rgb": [75, 0, 130],
        "color_hex": "#4B0082",
        "location": "Center of forehead",
        "location_ru": "Центр лба",
        "element": "Light",
        "element_ru": "Свет",
        "associated_with": "Intuition, insight, imagination, psychic abilities",
        "associated_with_ru": "Интуиция, проницательность, воображение, экстрасенсорные способности",
        "balanced_qualities": "Intuitive, perceptive, discerning, visionary",
        "balanced_qualities_ru": "Интуитивный, проницательный, рассудительный, дальновидный",
        "imbalanced_signs": "Lack of direction, poor intuition, headaches, insomnia",
        "imbalanced_signs_ru": "Отсутствие направления, плохая интуиция, головные боли, бессонница",
        "healing_practices": "Meditation, visualization, purple foods, reducing screen time, dream journaling",
        "healing_practices_ru": "Медитация, визуализация, фиолетовые продукты, сокращение времени у экрана, дневник сновидений"
    },
    {
        "name": "Crown",
        "name_ru": "Коронная",
        "sanskrit_name": "Sahasrara",
        "sanskrit_name_ru": "Сахасрара",
        "color_rgb": [148, 0, 211],
        "color_hex": "#9400D3",
        "location": "Top of head",
        "location_ru": "Макушка головы",
        "element": "Cosmic Energy",
        "element_ru": "Космическая энергия",
        "associated_with": "Spiritual connection, higher consciousness, enlightenment",
        "associated_with_ru": "Духовная связь, высшее сознание, просветление",
        "balanced_qualities": "Spiritually connected, wise, integrated, enlightened",
        "balanced_qualities_ru": "Духовно связанный, мудрый, интегрированный, просветленный",
        "imbalanced_signs": "Spiritual disconnection, materialism, cynicism, apathy",
        "imbalanced_signs_ru": "Духовная разобщенность, материализм, цинизм, апатия",
        "healing_practices": "Meditation, prayer, spending time in silence, fasting, connecting with nature",
        "healing_practices_ru": "Медитация, молитва, проведение времени в тишине, пост, связь с природой"
    }
]

# Text translations
app_text = {
    "en": {
        "page_title": "AURA STUDIO",
        "app_title": "AURA STUDIO",
        "app_intro": "Application for displaying the results of psycho-energetic diagnostics of energy centers and biofield. Developed at the Research Center for Initiology and Transpersonal Psychology. Application author and creator V. P. Lazarenko. Designed for professional psychics. Recommended for diagnostics starting from the 1st stage of Initiology using the method of psychic vision, biolocation on a 100% scale. The diagnostic data needs to be set in the application settings to obtain the original image of chakras and biofield in accordance with the diagnostic results.",
        "client_info_header": "Client Information",
        "fullname": "Full Name",
        "birthdate": "Date of Birth",
        "phone": "Phone Number",
        "email": "Email",
        "save_client": "Save Client Information",
        "param_header": "Energy Center Parameters",
        "param_desc": "Adjust the energy level for each chakra (0-100%):",
        "energy_suffix": "Energy",
        "reset_button": "Reset All to 100%",
        "visual_header": "Energy & Biofield Visualization",
        "view_mode": "Visualization Mode",
        "view_2d": "2D View",
        "view_3d": "3D View",
        "view_3d_help": "3D visualization allows you to rotate and zoom for a more immersive experience",
        "info_header": "Chakra Information",
        "info_intro": "Understanding your chakras can help you identify energy imbalances and areas for personal growth. Below is detailed information about each chakra.",
        "location": "Location",
        "current_energy": "Current Energy Level",
        "element": "Element",
        "associated_with": "Associated With",
        "balanced_qualities": "Balanced Qualities",
        "imbalanced_signs": "Imbalanced Signs", 
        "healing_practices": "Healing Practices",
        "footer": "Developed at the Research Center for Initiology and Transpersonal Psychology",
        
        # New diagnostic report analysis texts
        "report_upload_header": "Bioresonance Diagnostics Report Upload",
        "report_upload_info": "Upload a bioresonance diagnostics report in PDF format to automatically analyze and transform the data into chakra and biofield visualizations.",
        "upload_button": "Upload Report",
        "processing_report": "Processing report...",
        "analyzing_report": "Analyzing diagnostic report...",
        "report_processed": "Report processed successfully!",
        "report_error": "Error processing report",
        "apply_report_results": "Apply Results to Visualization",
        "report_analysis_header": "Report Analysis Results",
        "parameter": "Parameter",
        "measured_value": "Measured Value",
        "normal_range": "Normal Range",
        "status": "Status",
        "normal": "Normal",
        "abnormal": "Abnormal",
        "high": "High",
        "low": "Low",
        "report_info": "Report Information",
        "diagnostic_results": "Diagnostic Results",
        "chakra_impact": "Chakra Impact Analysis",
        "estimated_impact": "Estimated impact on chakras based on diagnostic results:",
        "use_manual_values": "Return to Manual Mode",
        "diagnostic_data_used": "Using diagnostic data from the report",
        "chakra_values_auto_calculated": "Chakra energy values are automatically calculated from the diagnostic data. Manual adjustments are not available.",
        "no_diagnostic_data": "No diagnostic data available",
        "please_upload_report": "Please upload a diagnostic report to visualize chakra energies based on data analysis.",
        "chakra_energy_values": "Current Energy Values",
        "no_chakra_data_in_report": "No chakra energy data found in the report. The report may be incomplete or in an unsupported format.",
        "no_report_for_aura": "No diagnostic report data available for aura photo",
        "please_upload_report_for_aura": "Please upload a diagnostic report first to generate an aura photo based on authentic data.",
        
        # Organ visualization texts
        "organ_visualization_tab": "Organ Visualization",
        "organ_visualization_info": "This visualization shows the state of the body's organs based on diagnostic data. Hover over an organ to see detailed information.",
        "healthy_organ": "Healthy",
        "inflamed_organ": "Inflamed",
        "weakened_organ": "Weakened",
        "damaged_organ": "Damaged",
        "no_data_organ": "No data available",
        "organ_detail_header": "Organ Details",
        "related_parameters": "Related Diagnostic Parameters",
        "select_organ": "Select an organ from the dropdown",
        "organ_detail_image": "Detailed organ view",
        "no_detailed_image": "Detailed image not available for this organ"
    },
    "ru": {
        "page_title": "AURA STUDIO",
        "app_title": "AURA STUDIO",
        "app_intro": "Приложение для отображения результатов психо-энергетической диагностики энергоцентров и биополя. Разработано в НИЦ Инициологии и трансперсональной психологии. Автор и создатель приложения В. П. Лазаренко. Предназначено для профессиональных экстрасенсов. Рекомендовано для проведения диагностики начиная с 1 ступени Инициологии по методу психического видения, биолокации по 100% шкале. Данные диагностики необходимо установить в настройках приложения для получения оригинального изображения чакр и биополя в соответствии с результатами диагностики.",
        "client_info_header": "Информация о Клиенте",
        "fullname": "ФИО",
        "birthdate": "Дата Рождения",
        "phone": "Телефон",
        "email": "Email",
        "save_client": "Сохранить Информацию",
        "param_header": "Параметры Энергоцентров",
        "param_desc": "Отрегулируйте уровень энергии для каждого энергоцентра (0-100%):",
        "energy_suffix": "Энергия",
        "reset_button": "Сбросить Все до 100%",
        "visual_header": "Визуализация Энергии и Биополя",
        "view_mode": "Режим Визуализации",
        "view_2d": "2D Вид",
        "view_3d": "3D Вид",
        "view_3d_help": "3D визуализация позволяет вращать и масштабировать для более иммерсивного опыта",
        "info_header": "Информация о Чакрах",
        "info_intro": "Понимание ваших чакр может помочь определить энергетические дисбалансы и области для личностного роста. Ниже представлена подробная информация о каждой чакре.",
        "location": "Расположение",
        "current_energy": "Текущий Уровень Энергии",
        "element": "Элемент",
        "associated_with": "Связана с",
        "balanced_qualities": "Качества при Балансе",
        "imbalanced_signs": "Признаки Дисбаланса",
        "healing_practices": "Практики для Исцеления",
        "footer": "Разработано в НИЦ Инициологии и трансперсональной психологии",
        
        # Новые тексты для анализа отчетов диагностики
        "report_upload_header": "Загрузка Отчета Биорезонансной Диагностики",
        "report_upload_info": "Загрузите отчет биорезонансной диагностики в формате PDF для автоматического анализа и преобразования данных в визуализацию чакр и биополя.",
        "upload_button": "Загрузить Отчет",
        "processing_report": "Обработка отчета...",
        "analyzing_report": "Анализ диагностического отчета...",
        "report_processed": "Отчет успешно обработан!",
        "report_error": "Ошибка обработки отчета",
        "apply_report_results": "Применить Результаты к Визуализации",
        "report_analysis_header": "Результаты Анализа Отчета",
        "parameter": "Параметр",
        "measured_value": "Измеренное Значение",
        "normal_range": "Диапазон Нормы",
        "status": "Статус",
        "normal": "Норма",
        "abnormal": "Отклонение",
        "high": "Повышен",
        "low": "Понижен",
        "report_info": "Информация об Отчете",
        "diagnostic_results": "Результаты Диагностики",
        "chakra_impact": "Анализ Влияния на Чакры",
        "estimated_impact": "Предполагаемое влияние на чакры на основе результатов диагностики:",
        "use_manual_values": "Вернуться в Ручной Режим",
        "diagnostic_data_used": "Используются данные из диагностического отчета",
        "chakra_values_auto_calculated": "Значения энергии чакр автоматически рассчитаны из данных диагностики. Ручная настройка не доступна.",
        "no_diagnostic_data": "Нет данных диагностики",
        "please_upload_report": "Пожалуйста, загрузите диагностический отчет для визуализации энергии чакр на основе анализа данных.",
        "chakra_energy_values": "Текущие значения энергии",
        "no_chakra_data_in_report": "В отчете не найдены данные об энергии чакр. Отчет может быть неполным или в неподдерживаемом формате.",
        "no_report_for_aura": "Нет данных диагностического отчета для фото ауры",
        "please_upload_report_for_aura": "Пожалуйста, сначала загрузите диагностический отчет, чтобы создать фото ауры на основе настоящих данных.",
        
        # Органная визуализация
        "organ_visualization_tab": "Визуализация Органов",
        "organ_visualization_info": "Эта визуализация показывает состояние органов тела на основе данных диагностики. Выберите орган из списка для просмотра подробной информации.",
        "healthy_organ": "Здоровый",
        "inflamed_organ": "Воспаленный",
        "weakened_organ": "Ослабленный",
        "damaged_organ": "Поврежденный",
        "no_data_organ": "Нет данных",
        "organ_detail_header": "Информация об Органе",
        "related_parameters": "Связанные Диагностические Параметры",
        "select_organ": "Выберите орган для просмотра подробностей",
        "organ_detail_image": "Детальное изображение органа",
        "no_detailed_image": "Детальное изображение для этого органа отсутствует"
    }
}
